[package]
name = "semvercli"
version = "0.0.1"
authors = ["Kiril Zvezdarov <kzvezdarov@gmail.com>"]
edition = "2018"

[dependencies]
toml_edit = "0.1.3"
semver = "0.9.0"
clap = "2.33.0"

[dev-dependencies]
proptest = "0.9.4"
tempfile = "3.0.8"
